### ISSUE TITLE
Cannot build solutions that contain multiple projects

### ISSUE THREAD

**Issue by MyIsaak** [KishoreIthadi/DotNet-Core-Essentials#24]
It appears when building multi project solutions one receives the error: `MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.`

To reproduce this issue:
1. Clone an example repo that has multiple projects (e.g `https://github.com/fo-dicom/fo-dicom.git`)
2. Open in VSCode and view solutions in `Solution Explorer` menu
3. Right click a specific solution and select `build` from dropdown menu.
![screenshot from 2018-05-13 15-04-09](https://user-images.githubusercontent.com/4984415/39967650-a3d972a6-56bf-11e8-9e49-bad264fd299a.png)

Expected result:
Runs `dotnet build {Solution file}` to build specific solution

Actual result:
Runs `dotnet build` without specifying solution file. This generates an error as shown above.

My environment settings: `dotnet --info`

```
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```

This should be a simple issue to fix, hopefully someone takes on the challenge. It's an annoyance especially when dealing with large complex projects that Visual Studio 2018 can solve instead.

**Comment by KishoreIthadi** [comment]
Is this question in context with Dotnet-Core-Essentials? Looks like the DCE extension is not installed in your IDE according to the image in the description. All the DCE commands start with "DEC: " as the prefix.

![image](https://user-images.githubusercontent.com/19744167/40301680-71b92644-5d0a-11e8-88b9-96304351b2d8.png)

**Comment by MyIsaak** [comment]
Sorry my bad I had another extension installed that adds a solution explorer window, and I mistakenly blamed you're plugin instead of the other.

The DCE:Build only pops up when directly selecting the .sln file (which should be normal).

Excellent plugin nevertheless ;)

**Comment by KishoreIthadi** [comment]
Thanks for your support!
