### ISSUE TITLE
Fails to update in extension pack

### ISSUE THREAD

**Issue by s-albert** [KishoreIthadi/DotNet-Core-Essentials#25]
I created an extension pack (https://marketplace.visualstudio.com/items?itemName=salbert.awesome-dotnetcore-pack), which contains DotNet-Core-Essentials. Every time when I change the extension pack and deploy the new version, "dotnet-core-essentials" tries to update version 0.0.4 and fails, which implies that the extension pack also fails. The workaround is to uninstall DotNet-Core-Essentials and install the extension pack. Then the most recent version of dotnet-core-essentials is installed, but next time the extension pack is updated (without changing DotNet-Core-Essentials), it tries to update DotNet-Core-Essentials again and fails.... I tested this behaviour on two different pcs.

**Comment by KishoreIthadi** [comment]
Getting this error

![error](https://user-images.githubusercontent.com/19744167/40409471-ae74b97a-5e88-11e8-953c-b9f47f3d3a4c.png)

**Comment by s-albert** [comment]
But how to fix it? In my exension pack I have only this property, which seems to be correct:
  "extensionDependencies": [
    "pflannery.vscode-versionlens",
    "mycelo.embrace",
    "eamodio.gitlens",
    "christian-kohler.path-intellisense",
    "ms-vscode.csharp",
    "jchannon.csharpextensions",
    "k--kato.docomment",
    "josephwoodward.vscodeilviewer",
    "kishoreithadi.dotnet-core-essentials",
    "formulahendry.dotnet-test-explorer",
    "craigthomas.supersharp",
    "jorgeserrano.vscode-csharp-snippets",
    "quicktype.quicktype",
    "patrys.vscode-code-outline",
    "Gruntfuggly.todo-tree"
  ]

**Comment by KishoreIthadi** [comment]
looking into it. will update on this ASAP.

**Comment by s-albert** [comment]
Thank you, I will add DCE when the fix is released in VSCode.

**Comment by KishoreIthadi** [comment]
@s-albert This issue is resolved now, I don't think that Microsoft has to release an update for this.

I have cloned your repository and created an extension "DCETest" which includes DCE extension. It is getting installed without any issue.

Doubled checked in 2 more machines and is working as expected.

You can now add DCE and release a new version of the extension!

**Comment by s-albert** [comment]
Done. (release 1.7.0)
