### ISSUE TITLE
Missing instructional animations

### ISSUE THREAD

**Issue by PeterWone** [KishoreIthadi/DotNet-Core-Essentials#26]
For images referenced by the readme.md, assets appear to be missing, or the references may be broken.

![capture](https://user-images.githubusercontent.com/5498936/40147512-4d5017b4-59ad-11e8-8c3f-2170befb3626.PNG)

**Comment by KishoreIthadi** [comment]
Created pending gifs. You should be able to see them in vscode and GitHub readme.
