### ISSUE TITLE
DCE Add Project Reference - "source" and "destination" are confusing

### ISSUE THREAD

**Issue by KillyMXI** [KishoreIthadi/DotNet-Core-Essentials#38]
I can't remember which logic it follows:

* source project will be modified to include a reference pointing to target project
* target project will receive a reference to source project

Some explanation is needed when these inputs are shown, to clear the confusion.

**Comment by ManojVeeranala** [comment]
@KillyMXI it follows 
"source project will be modified to include a reference pointing to target project"

the first project you select will have a reference of the next selected project. we will try to improvise this
