### ISSUE TITLE
DCE: Need Core SDK 2.0.3 or higher

### ISSUE THREAD

**Issue by SquallHalle** [KishoreIthadi/DotNet-Core-Essentials#45]
Error Message:
DCE: Need Core SDK 2.0.3 or higher

Enviroment:
` $ lsb_release -a`
`No LSB modules are available.`
`Distributor ID:	Ubuntu`
`Description:	Ubuntu 19.04`
`Release:	19.04`
`Codename:	disco`

`$ dotnet --version`
`3.0.100-preview9-014004`

`$ which dotnet`
`/snap/bin/dotnet`

**Comment by ManojVeeranala** [comment]
Thanks @SquallHalle for finding the issue, It is fixed and available in DCE 0.0.8 version. Please update your extension.
